"""Gera PDF do Roteiro de Testes Manuais."""
from fpdf import FPDF

class TestPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, 'muv.log - Roteiro de Testes Manuais', 0, 0, 'L')
            self.cell(0, 10, f'Pagina {self.page_no()}', 0, 1, 'R')
            self.line(10, 15, 200, 15)
            self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'muv.log 2026', 0, 0, 'C')

    def section(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(13, 148, 136)
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(13, 148, 136)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def subsection(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(30, 41, 59)
        self.cell(0, 7, title, 0, 1, 'L')
        self.ln(1)

    def test_item(self, num, desc, expected=''):
        self.set_font('Helvetica', '', 9)
        self.set_text_color(51, 51, 51)
        # Checkbox
        x = self.get_x()
        y = self.get_y()
        self.rect(x, y + 1, 4, 4)
        self.set_x(x + 6)
        self.set_font('Helvetica', 'B', 9)
        self.cell(12, 5, num, 0, 0)
        self.set_font('Helvetica', '', 9)
        self.multi_cell(0, 5, desc)
        if expected:
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(100, 100, 100)
            self.set_x(x + 18)
            self.multi_cell(0, 4, f'Esperado: {expected}')
            self.set_text_color(51, 51, 51)
        self.ln(1)

def create_test_pdf():
    pdf = TestPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Capa
    pdf.add_page()
    pdf.ln(30)
    pdf.set_font('Helvetica', 'B', 28)
    pdf.set_text_color(13, 148, 136)
    pdf.cell(0, 12, 'muv.log', 0, 1, 'C')
    pdf.ln(5)
    pdf.set_font('Helvetica', '', 16)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, 'Roteiro de Testes Manuais', 0, 1, 'C')
    pdf.ln(3)
    pdf.set_font('Helvetica', '', 12)
    pdf.cell(0, 8, 'Versao 1.0 - Setembro 2026', 0, 1, 'C')
    pdf.cell(0, 8, '147 testes em 13 secoes', 0, 1, 'C')
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, 'Marque [x] ao completar cada teste. Anote observacoes.', 0, 1, 'C')

    # 1. Acesso e Autenticacao
    pdf.add_page()
    pdf.section('1. Acesso e Autenticacao')
    pdf.subsection('1.1 Login - Caminho Feliz')
    pdf.test_item('1.1.1', 'Login Super Admin: /login -> email correto -> senha correta -> Entrar', 'Dashboard /platform')
    pdf.test_item('1.1.2', 'Login Admin tenant: /login -> email admin com tenant -> senha -> Entrar', 'Dashboard /admin')
    pdf.test_item('1.1.3', 'Login Estabelecimento: /client/login -> email/senha -> Entrar', 'Dashboard /client')
    pdf.test_item('1.1.4', 'Login Entregador Plataforma: /login -> email/senha -> Entrar', 'Dashboard /dashboard')
    pdf.test_item('1.1.5', 'Login Entregador Proprio: /own-driver/login -> tel + PIN -> Entrar', 'Dashboard proprio')

    pdf.subsection('1.2 Login - Testes de Esforco')
    pdf.test_item('1.2.1', 'Senha errada -> deve mostrar "Credenciais invalidas"', 'Erro 401')
    pdf.test_item('1.2.2', 'Email inexistente -> deve mostrar "Credenciais invalidas"', 'Erro 401')
    pdf.test_item('1.2.3', 'Campos vazios -> deve mostrar erro de validacao', 'Erro 400')
    pdf.test_item('1.2.4', 'Email sem @ -> deve mostrar erro', 'Erro de validacao')
    pdf.test_item('1.2.5', "SQL Injection: ' OR 1=1 -- no email -> NAO deve logar", 'Bloqueado')
    pdf.test_item('1.2.6', 'Usuario suspenso tenta logar -> deve bloquear', 'Erro 403')
    pdf.test_item('1.2.7', 'Usuario inativo (pendente) tenta logar -> deve bloquear', 'Mensagem pendente')
    pdf.test_item('1.2.8', 'Tenant inativo -> usuario desse tenant tenta logar', 'Bloqueado')
    pdf.test_item('1.2.9', 'Rate limiting: 6 tentativas em 1 min -> deve bloquear apos 5', 'Bloqueio temporario')
    pdf.test_item('1.2.10', 'Token expiracao: login -> aguarde 4h -> tente acao', 'Desloga')
    pdf.test_item('1.2.11', 'Email com espacos: " email@test.com " -> deve tratar', 'Aceitar ou rejeitar')
    pdf.test_item('1.2.12', 'Email com acentos: tste@email.com -> deve tratar sem crash', 'Sem crash')

    pdf.subsection('1.3 Cadastro')
    pdf.test_item('1.3.1', 'Cadastro Entregador: preencha tudo -> Cadastrar', 'Conta criada (pendente)')
    pdf.test_item('1.3.2', 'Cadastro Estabelecimento: preencha -> Cadastrar', 'Conta criada (pendente)')
    pdf.test_item('1.3.3', 'Link com praca: acesse link com ?square_id=X', 'Praca pre-selecionada')
    pdf.test_item('1.4.1', 'Email duplicado -> deve rejeitar', 'Erro')
    pdf.test_item('1.4.2', 'Senha curta (3 chars) -> deve rejeitar', 'Minimo 6')
    pdf.test_item('1.4.3', 'Campos obrigatorios vazios -> deve rejeitar', 'Erro')
    pdf.test_item('1.4.4', 'CPF invalido: "123" -> deve aceitar ou rejeitar', 'Tratar sem crash')
    pdf.test_item('1.4.5', 'Telefone invalido: "abc" -> deve tratar', 'Sem crash')
    pdf.test_item('1.4.6', 'Cadastro sem internet -> deve mostrar erro', 'Erro de conexao')

    pdf.subsection('1.5 Logout e Sessao')
    pdf.test_item('1.5.1', 'Logout -> deve limpar token e redirecionar', '/login')
    pdf.test_item('1.5.2', 'Acessar rota protegida apos logout -> redireciona', '/login')
    pdf.test_item('1.5.3', 'Duas abas: logout em uma -> outra funciona ate refresh', 'OK')
    pdf.test_item('1.5.4', 'Token invalido no localStorage -> recarrega -> desloga', '/login')

    # 2. Super Admin
    pdf.add_page()
    pdf.section('2. Super Admin')
    pdf.subsection('2.1 Dashboard Global')
    pdf.test_item('2.1.1', 'Dashboard /platform carrega com metricas', 'Totais visiveis')
    pdf.test_item('2.1.2', 'Dados batem com realidade do banco', 'Numeros corretos')
    pdf.test_item('2.1.3', 'Alternar para painel admin -> dados do tenant', 'OK')

    pdf.subsection('2.2 Gerenciar Tenants')
    pdf.test_item('2.2.1', 'Criar tenant: nome, slug -> Salvar', 'Tenant criado')
    pdf.test_item('2.2.2', 'Editar tenant: mudar nome/cor -> Salvar', 'Atualizado')
    pdf.test_item('2.2.3', 'Desativar tenant -> status muda', 'Inativo')
    pdf.test_item('2.2.4', 'Login com tenant desativado -> bloqueia', 'Bloqueado')
    pdf.test_item('2.2.5', 'Reativar tenant -> login funciona', 'OK')
    pdf.test_item('2.2.6', 'Excluir tenant com dados -> protege', 'Confirmacao')

    pdf.subsection('2.3 Gerenciar Admins')
    pdf.test_item('2.3.1', 'Criar admin -> senha gerada', 'Admin criado')
    pdf.test_item('2.3.2', 'Editar admin -> atualiza', 'OK')
    pdf.test_item('2.3.3', 'Resetar senha -> nova senha gerada', 'OK')
    pdf.test_item('2.3.4', 'Excluir ultimo admin do tenant -> protege', 'Bloqueado')
    pdf.test_item('2.3.5', 'Excluir admin com pedidos -> confirmacao', 'Confirmacao')

    # 3. Admin do Tenant
    pdf.add_page()
    pdf.section('3. Admin do Tenant')
    pdf.subsection('3.1 Dashboard')
    pdf.test_item('3.1.1', 'Dashboard /admin carrega com metricas do tenant', 'Dados visiveis')
    pdf.test_item('3.1.2', 'Seletor de praca filtra dados', 'Filtro funciona')
    pdf.test_item('3.1.3', 'Mapa ao vivo mostra entregadores', 'Marcadores visiveis')
    pdf.test_item('3.1.4', 'Atualizacao automatica a cada 15s', 'Mapa atualiza')

    pdf.subsection('3.2 Estabelecimentos')
    pdf.test_item('3.2.1', 'Criar estabelecimento com todos os campos', 'Criado')
    pdf.test_item('3.2.2', 'Geocodificar endereco -> preenche lat/lng', 'Coordenadas OK')
    pdf.test_item('3.2.3', 'Editar estabelecimento', 'Atualizado')
    pdf.test_item('3.2.4', 'Ativar/Desativar estabelecimento', 'Status muda')
    pdf.test_item('3.2.5', 'Link de cadastro -> gerar, copiar, acessar', 'Formulario abre')
    pdf.test_item('3.2.6', 'Excluir com pedidos -> protege', 'Confirmacao')

    pdf.subsection('3.3 Entregadores')
    pdf.test_item('3.3.1', 'Criar entregador', 'Criado')
    pdf.test_item('3.3.2', 'Transferir entre pracas', 'Transferido')
    pdf.test_item('3.3.3', 'Suspender -> fica offline automaticamente', 'Offline')
    pdf.test_item('3.3.4', 'Login de entregador suspenso -> bloqueia', 'Bloqueado')
    pdf.test_item('3.3.5', 'Reativar -> pode logar novamente', 'OK')
    pdf.test_item('3.3.6', 'Converter para proprio', 'EstablishmentDriver criado')
    pdf.test_item('3.3.7', 'Converter de volta para plataforma', 'Reativado')
    pdf.test_item('3.3.8', 'Link de cadastro de entregador', 'Link funciona')

    pdf.subsection('3.4 Pedidos')
    pdf.test_item('3.4.1', 'Lancar pedido manual (todos campos)', 'PENDING')
    pdf.test_item('3.4.2', 'Editar pedido', 'Atualizado')
    pdf.test_item('3.4.3', 'Atribuir entregador manualmente', 'ACCEPTED')
    pdf.test_item('3.4.4', 'Cancelar pedido -> estorna saldo', 'CANCELLED + estorno')
    pdf.test_item('3.4.5', 'Chamar Entregadores -> notifica', 'Notificacao enviada')
    pdf.test_item('3.4.6', 'Filtrar por status', 'Filtro funciona')
    pdf.test_item('3.4.7', 'Filtrar por data', 'Filtro funciona')
    pdf.test_item('3.4.8', 'Exportar CSV', 'Arquivo baixado')

    pdf.subsection('3.5 Financeiro')
    pdf.test_item('3.5.1', 'Dashboard financeiro -> receita, custos', 'Dados visiveis')
    pdf.test_item('3.5.2', 'Gerar fatura com link PIX', 'Fatura criada')
    pdf.test_item('3.5.3', 'Processar saque de entregador', 'Pago')

    pdf.subsection('3.6 Configuracoes')
    pdf.test_item('3.6.1', 'White-label: mudar logo, cores', 'Layout muda')
    pdf.test_item('3.6.2', 'Tabela de preco com tarifa fixa', 'Salva')
    pdf.test_item('3.6.3', 'Precos dinamicos: taxa de chuva', 'Aplica no frete')
    pdf.test_item('3.6.4', 'Raio GPS configuravel', 'Afeta validacao')

    pdf.subsection('3.7 Esforco - Admin')
    pdf.test_item('3.7.1', 'Criar estabelecimento sem campos obrigatorios', 'Rejeita')
    pdf.test_item('3.7.2', 'Pedido com valor negativo', 'Rejeita')
    pdf.test_item('3.7.3', 'Pedido sem itens', 'Rejeita')
    pdf.test_item('3.7.4', 'Editar pedido ja entregue', 'Bloqueia')
    pdf.test_item('3.7.5', 'Trocar praca rapidamente -> dados nao misturam', 'OK')
    pdf.test_item('3.7.6', 'Exportar com 0 pedidos', 'Arquivo vazio')
    pdf.test_item('3.7.7', 'Suspender entregador com pedido ativo', 'Pedido visivel')
    pdf.test_item('3.7.8', 'Muitos pedidos de uma vez (20)', 'Sistema aguenta')

    # 4. Estabelecimento
    pdf.add_page()
    pdf.section('4. Estabelecimento (Cliente)')
    pdf.subsection('4.1 Dashboard')
    pdf.test_item('4.1.1', 'Dashboard /client carrega pedidos do dia', 'Dados visiveis')
    pdf.test_item('4.1.2', 'Mapa com entregadores proximos', 'Marcadores visiveis')
    pdf.test_item('4.1.3', 'Rastreamento ao vivo do entregador', 'Posicao atualiza')

    pdf.subsection('4.2 Criar Pedidos')
    pdf.test_item('4.2.1', 'Pedido completo -> Calcular frete -> Enviar', 'PENDING com frete')
    pdf.test_item('4.2.2', 'Frete por KM: distancia x preco/km', 'Valor correto')
    pdf.test_item('4.2.3', 'Frete fixo: se praca tem tarifa fixa', 'Valor fixo')
    pdf.test_item('4.2.4', 'Pedido agendado com data futura', 'SCHEDULED')
    pdf.test_item('4.2.5', 'Acompanhar pedido em tempo real', 'Status atualiza')
    pdf.test_item('4.2.6', 'Cancelar pedido antes de ser aceito', 'CANCELLED')
    pdf.test_item('4.2.7', 'Avaliar entregador apos entrega', 'Avaliacao salva')
    pdf.test_item('4.2.8', 'Link de rastreio em aba anonima', 'Mostra sem login')

    pdf.subsection('4.3 Entregadores Proprios')
    pdf.test_item('4.3.1', 'Cadastrar entregador proprio', 'Criado')
    pdf.test_item('4.3.2', 'Definir PIN de 4 digitos', 'Salvo')
    pdf.test_item('4.3.3', 'Login com PIN no /own-driver/login', 'Loga')
    pdf.test_item('4.3.4', 'Atribuir a pedido', 'Vinculado')
    pdf.test_item('4.3.5', 'Ativar/Desativar entregador', 'Status muda')

    pdf.subsection('4.4 Esforco - Estabelecimento')
    pdf.test_item('4.4.1', 'Pedido sem endereco -> rejeita', 'Erro')
    pdf.test_item('4.4.2', 'Pedido sem cliente -> rejeita', 'Erro')
    pdf.test_item('4.4.3', 'Valor muito alto (999999.99)', 'Sem crash')
    pdf.test_item('4.4.4', 'Valor zero', 'Aceita ou rejeita')
    pdf.test_item('4.4.5', 'Texto em campo numerico ("abc")', 'Trata sem crash')
    pdf.test_item('4.4.6', 'Cancelar pedido ja entregue', 'Bloqueia')
    pdf.test_item('4.4.7', 'Nome com <script> (XSS)', 'Exibe como texto')
    pdf.test_item('4.4.8', 'Dois pedidos rapidos', 'Ambos criam')
    pdf.test_item('4.4.9', 'Endereco com 500+ caracteres', 'Sem crash')
    pdf.test_item('4.4.10', 'Avaliar pedido nao entregue', 'Bloqueia')

    # 5. Entregador
    pdf.add_page()
    pdf.section('5. Entregador Plataforma')
    pdf.subsection('5.1 Dashboard')
    pdf.test_item('5.1.1', 'Dashboard /dashboard com stats', 'Ganhos, entregas')
    pdf.test_item('5.1.2', 'Mapa centralizado na cidade', 'Posicao correta')
    pdf.test_item('5.1.3', 'MuvScore: pontos e nivel', 'Nivel atual')
    pdf.test_item('5.1.4', 'Ganhos estimados com % do backend', 'Valor correto')

    pdf.subsection('5.2 Status Online/Offline')
    pdf.test_item('5.2.1', 'Ficar online', 'Status muda')
    pdf.test_item('5.2.2', 'GPS atualiza ao andar', 'Posicao atualiza')
    pdf.test_item('5.2.3', 'Ficar offline', 'Para de receber ofertas')
    pdf.test_item('5.2.4', 'Admin ve entregador no mapa', 'Marcador aparece')

    pdf.subsection('5.3 Receber e Aceitar')
    pdf.test_item('5.3.1', 'Receber oferta com sirene', 'Popup + som')
    pdf.test_item('5.3.2', 'Aceitar pedido', 'ACCEPTED')
    pdf.test_item('5.3.3', 'Rejeitar pedido', 'Repassa para proximo')
    pdf.test_item('5.3.4', 'Timeout de oferta', 'Repassa automatico')
    pdf.test_item('5.3.5', 'Som de sirene alto', 'Audivel em moto')

    pdf.subsection('5.4 Fluxo de Entrega')
    pdf.test_item('5.4.1', 'Navegar ate restaurante', 'Google Maps ou Waze')
    pdf.test_item('5.4.2', 'Confirmar coleta com codigo correto', 'PICKED_UP')
    pdf.test_item('5.4.3', 'Codigo de coleta errado', 'Rejeita')
    pdf.test_item('5.4.4', 'Confirmar coleta com foto', 'Foto salva')
    pdf.test_item('5.4.5', 'Navegar ate cliente', 'Mapa abre')
    pdf.test_item('5.4.6', 'Confirmar entrega com codigo', 'DELIVERED')
    pdf.test_item('5.4.7', 'Confirmar entrega com foto', 'Foto salva')
    pdf.test_item('5.4.8', 'Foto de prova visivel para estabelecimento', 'Foto aparece')

    pdf.subsection('5.5 Financeiro')
    pdf.test_item('5.5.1', 'Ver ganhos na carteira', 'Saldo correto')
    pdf.test_item('5.5.2', 'Solicitar saque', 'Solicitacao criada')
    pdf.test_item('5.5.3', 'Saque acima do saldo', 'Rejeita')
    pdf.test_item('5.5.4', 'Saldo atualiza apos entrega', 'Atualiza')
    pdf.test_item('5.5.5', 'Locked balance aparece', 'Valor bloqueado')

    pdf.subsection('5.6 Esforco - Entregador')
    pdf.test_item('5.6.1', 'Aceitar sem internet -> salva offline', 'IndexedDB')
    pdf.test_item('5.6.2', 'Internet volta -> sincroniza', 'Auto-sync')
    pdf.test_item('5.6.3', '2 entregadores aceitam mesmo pedido', 'So 1 aceita')
    pdf.test_item('5.6.4', 'GPS desligado -> atualizar posicao', 'Sem crash')
    pdf.test_item('5.6.5', 'Confirmar entrega longe do local', 'Bloqueia (se raio)')
    pdf.test_item('5.6.6', 'Saque de R$0', 'Rejeita')
    pdf.test_item('5.6.7', 'Saque negativo (-10)', 'Rejeita')
    pdf.test_item('5.6.8', '5 saques rapidos', 'So processa os cabiveis')

    # 6-13
    pdf.add_page()
    pdf.section('6. Entregador Proprio')
    pdf.test_item('6.1', 'Login com PIN', 'Loga')
    pdf.test_item('6.2', 'PIN errado', 'Rejeita')
    pdf.test_item('6.3', 'Ver pedidos atribuidos', 'So os seus')
    pdf.test_item('6.4', 'Confirmar coleta', 'Status atualiza')
    pdf.test_item('6.5', 'Confirmar entrega', 'Status atualiza')
    pdf.test_item('6.6', 'Ver ganhos', 'Valores corretos')
    pdf.test_item('6.7', 'Offline (modo aviao) -> reconectar -> sincroniza', 'Auto-sync')

    pdf.section('7. Notificacoes')
    pdf.test_item('7.1', 'Push de novo pedido para entregador', 'Vibra + mostra')
    pdf.test_item('7.2', 'Push com app fechado', 'Notificacao aparece')
    pdf.test_item('7.3', 'Sino de notificacoes', 'Lista aparece')
    pdf.test_item('7.4', 'Marcar notificacao como lida', 'Marca')
    pdf.test_item('7.5', 'Marcar todas como lidas', 'Todas marcam')
    pdf.test_item('7.6', 'Admin recebe push de cadastro pendente', 'Notifica')
    pdf.test_item('7.7', 'WhatsApp com entregador -> wa.me/ abre', 'Mensagem pronta')

    pdf.section('8. Rastreio Publico')
    pdf.test_item('8.1', 'Acessar /track/TOKEN sem login', 'Mostra status')
    pdf.test_item('8.2', 'Status atualizado no link', 'Atualiza')
    pdf.test_item('8.3', 'Token invalido', 'Erro')
    pdf.test_item('8.4', 'Localizacao do entregador no mapa', 'Posicao visivel')

    pdf.section('9. Exportacao e Importacao')
    pdf.test_item('9.1', 'Exportar pedidos CSV', 'Arquivo baixado')
    pdf.test_item('9.2', 'Exportar entregadores CSV', 'Arquivo baixado')
    pdf.test_item('9.3', 'CSV abre no Excel corretamente', 'Colunas OK')
    pdf.test_item('9.4', 'Importar pedidos via CSV', 'Pedidos criados')
    pdf.test_item('9.5', 'CSV com dados invalidos', 'Erros por linha')
    pdf.test_item('9.6', 'CSV vazio', 'Sem crash')

    pdf.section('10. PWA e Offline')
    pdf.test_item('10.1', 'Instalar como app (Android)', 'Instala')
    pdf.test_item('10.2', 'Instalar como app (iPhone)', 'Instala')
    pdf.test_item('10.3', 'Instalar como app (Desktop)', 'Instala')
    pdf.test_item('10.4', 'App abre sem barra do browser', 'Standalone')
    pdf.test_item('10.5', 'Modo aviao -> ver pedidos', 'Pedidos carregados')
    pdf.test_item('10.6', 'Modo aviao -> aceitar pedido', 'Salva local')
    pdf.test_item('10.7', 'Internet volta -> sincroniza', 'Auto-sync')

    pdf.section('11. Responsividade Mobile')
    pdf.test_item('11.1', 'Login cabe na tela (sem scroll horizontal)', 'OK')
    pdf.test_item('11.2', 'Dashboard admin -> sidebar colapsa', 'Colapsa')
    pdf.test_item('11.3', 'Toggle sidebar -> abre/fecha', 'Funciona')
    pdf.test_item('11.4', 'Menu mobile -> todos os itens', 'Completo')
    pdf.test_item('11.5', 'Mapa interativo (zoom/pan)', 'Funciona')
    pdf.test_item('11.6', 'Formularios nao sobrepoe', 'OK')
    pdf.test_item('11.7', 'Botoes clicaveis (tamanho adequado)', 'OK')

    pdf.section('12. Multi-Tenant')
    pdf.test_item('12.1', 'Admin ve so dados do seu tenant', 'Isolado')
    pdf.test_item('12.2', 'Entregador ve pedidos do seu tenant', 'Isolado')
    pdf.test_item('12.3', 'Estabelecimento ve so seus pedidos', 'Isolado')
    pdf.test_item('12.4', 'Tentar acessar dados de outro tenant', 'Bloqueado')
    pdf.test_item('12.5', 'Super admin ve tudo', 'Acesso global')

    pdf.section('13. Performance')
    pdf.test_item('13.1', '50 pedidos de uma vez', 'Sistema aguenta')
    pdf.test_item('13.2', '20 entregadores online', 'Mapa aguenta')
    pdf.test_item('13.3', 'Navegacao rapida entre paginas', 'Sem crash')
    pdf.test_item('13.4', 'Refresh durante acao', 'Recupera estado')
    pdf.test_item('13.5', 'Aba aberta por 1 hora', 'Continua OK')
    pdf.test_item('13.6', 'Multiplas abas (3)', 'Todas funcionam')

    # Salvar
    pdf.output('docs/ROTEIRO_TESTES_MANUAIS.pdf')
    print('PDF gerado: docs/ROTEIRO_TESTES_MANUAIS.pdf')

if __name__ == '__main__':
    create_test_pdf()
